---
- secret:
    name: SECRET_OPENSTACK_FLAVOR_MANAGER
    data:
      PYPI_API_TOKEN: !encrypted/pkcs1-oaep
        - ExrB71LLJk5aFG4hAl22AV27dVZoMPvTyZ6ZvLWeKjv00cUfMzjUNHW+E+JvTo2BP4OE4
          0D3v8FXZBJ5HODxffK6hXi9eIQ8oj7MYvu8i7lRl5hyqC9/rXUaJ+2kXseKMvUR1x2s8F
          LuZW5w2aoXOfqVMoKAhxopnC0u2iXNRa1uJ9kYT+tLntoveLV3+7bXqUh0r4PJt8d/oqB
          G/amp6UFBPsXQ7IMWi1x9AnzooHmWOeasrr1QxG6tgZSLcelMIU7/zo5xOxNoNqjlTUT/
          pDDO00HfhhQjILScxBZ4JOT/qs0oH3lpKxK0ZWn8/Xgwc0lMHfgYUgdTPMJbRmudqfq//
          OmhUu1h0WQdQjjJysc+725vaPsi5HQTvNQVhh6LZQiAYPSdJyMr4E4Rt75XVHtk3w3gws
          sx0IViiFGiMOVGpZ0uzWBPMdnXd9JFPhprIj4W85ry0xPAyb3TItNhdpxthmDEsXwHq9v
          NZaQnjvyB0GVq0UU5P6M+F9VFcascPOY+4XomYLs6SKVAnNuHlTBeJonlSqf62eH34XrK
          wj9Ld1g3B+VR0eozcnqMxh78APO52X1RYYUti0QNPNh50fk1eVapfNV19zCPRTRHYovR2
          6Jj6YNefzmb8N3O+eMZIgGSSbXnbhj2i8uhQ7UPVElwDSkG0DIAcRNkxZT4BE4=

- job:
    name: build-python-package
    run: playbooks/build-python-package.yml
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_FLAVOR_MANAGER

- project:
    merge-mode: "squash-merge"
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
        - tox-py310:
            vars:
              tox_envlist: test
    gate:
      jobs:
        - flake8
        - mypy
        - tox-py310:
            vars:
              tox_envlist: test
    periodic-daily:
      jobs:
        - flake8
        - mypy
        - tox-py310:
            vars:
              tox_envlist: test
    tag:
      jobs:
        - build-python-package
