---
- project:
    merge-mode: "squash-merge"
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
    gate:
      jobs:
        - flake8
        - mypy
    periodic-daily:
      jobs:
        - flake8
        - mypy
