---
- job:
    name: flavor-manager-integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    timeout: 3600
    roles:
      - zuul: osism/zuul-jobs
        name: devstack
    vars:
      devstack_services: "keystone n-api"

- project:
    merge-mode: "squash-merge"
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
        - tox:
            vars:
              tox_envlist: test
        - flavor-manager-integration-test
    gate:
      jobs:
        - flake8
        - mypy
        - tox:
            vars:
              tox_envlist: test
        - flavor-manager-integration-test
    periodic-daily:
      jobs:
        - flake8
        - mypy
        - tox:
            vars:
              tox_envlist: test
        - flavor-manager-integration-test
