---
- secret:
    name: SECRET_OPENSTACK_FLAVOR_MANAGER
    data:
      PYPI_API_TOKEN: !encrypted/pkcs1-oaep
        - y+Q3RQ8f4wECxOr6lj5n3A76zBXNIEWI+BN8V46uDrMqGmsZTew2SMDCbEFFwAE3P+Ji/
          ZByjWnoyTAZbs6i6iyeihk7/OS33i/AoC5IZfVUT4ceEhvXyuFfOUGJfNAmkMg1eMqDBY
          SQsiKk2UbkxGyG3RQWiwarcenoviOta8092AtpVWtJxsLM3tUlOQKdbQMf2WN3zXthGcE
          7Ihoq7OtaeoYxWUsl1pvebE2AIku9WH/bazTS5d6A+k6nyBtzwOsnmJ19shF7dcpJymc2
          1iQUrUNOyKzhV8ZGIdaJ4PmVjF9dbET26WYTL8ZXxm5C9sf9SlUJop9Q4qCpCbpwbzYaB
          rGwOuxuQHO0/y1g2eXfdoxRuJs+38Z7pYKt0JQHar675SJDV8dUjr4fL0s6biwQKYGa2o
          FI4axfNBA4LAWm3rNDdsjP3+yGHx7j/KdrLoKLTsadxk/66zuIfPfRGo6030F5rI5Rhy4
          ypTQddIQjz1i5R/itzRbGJZGWobpnl+j6rt4u6YZpwS6bSdk0WBq75GCvSI2lN0355hvF
          +UXt+DWtVzd8rwxJwAwINhR+t4yp5PuQMOeb4IcpL4baY1BHUAUkADLIhFhmPcmDXk+7D
          wwG03QW+0omlGT1USlW6VhqVcqcfxATXWfu8hUJmhur76yuQbTOnB9dQgkyPk8=

- job:
    name: openstack-flavor-manager-integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    # The deployment of Devstack can take more time than our default timeout.
    timeout: 7200
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- job:
    name: openstack-flavor-manager-publish-pypi-package
    parent: publish-pypi-package
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_FLAVOR_MANAGER
        pass-to-parent: true
    vars:
        pypi_twine_executable: "/tmp/venv/bin/python -m twine"

- project:
    merge-mode: "squash-merge"
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
        - openstack-flavor-manager-integration-test
        - python-black
        - tox:
             vars:
               tox_envlist: test
    periodic-daily:
      jobs:
        - flake8
        - mypy
        - openstack-flavor-manager-integration-test
        - python-black
        - tox:
             vars:
               tox_envlist: test
    tag:
      jobs:
        - openstack-flavor-manager-publish-pypi-package
