---
- project:
    merge-mode: "squash-merge"
    default-branch: main
    check:
      jobs:
        - flake8
        - mypy
        - tox-py310:
            vars:
              tox_envlist: test
    gate:
      jobs:
        - flake8
        - mypy
        - tox-py310:
            vars:
              tox_envlist: test
    periodic-daily:
      jobs:
        - flake8
        - mypy
        - tox-py310:
            vars:
              tox_envlist: test
